tools:
    php_changetracking:
        enabled: true
    php_code_sniffer:
        enabled: true
        config:
            standard: "PSR2"
# php_sim is used instead (scrutinizer can't run both php_sim and php_cpd
    php_sim:
        enabled: true
    php_cpd:
        enabled: false
    php_cs_fixer:
        enabled: false
    php_mess_detector:
        enabled: true
    php_pdepend:
        enabled: true
    php_analyzer:
        enabled: true
    php_code_coverage:
        enabled: true
#    external_code_coverage:
#        timeout: 600
