language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script: "make install"

script:
  - "make tests"
  - "make code-sniffer-cli"

after_script:
  - "php vendor/bin/coveralls -v"

notifications:
  irc:
    channels:
      - "chat.freenode.net#environaut"
    on_success: always
    on_failure: always
    use_notice: false
    skip_join: false
